# Generated by Django 5.1 on 2025-02-07 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blocos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Bloco',
                'verbose_name_plural': 'Blocos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Chaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponivel', models.BooleanField(default=True)),
                ('principal', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Chave',
                'verbose_name_plural': 'Chaves',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('hash_token', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('valor', models.CharField(max_length=512)),
                ('data_expiracao', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PessoasAutorizadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamecoapi.chaves')),
            ],
        ),
        migrations.CreateModel(
            name='Salas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='chamecoapi.blocos')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='chaves',
            name='sala',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chave', to='chamecoapi.salas'),
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=512)),
                ('id_cortex', models.IntegerField(unique=True)),
                ('setor', models.CharField(max_length=512)),
                ('tipo', models.CharField(max_length=512)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('autorizado_emprestimo', models.BooleanField(default=False)),
                ('chaves_autorizadas', models.ManyToManyField(through='chamecoapi.PessoasAutorizadas', to='chamecoapi.chaves')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='pessoasautorizadas',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamecoapi.usuarios'),
        ),
        migrations.AddField(
            model_name='chaves',
            name='usuarios_autorizados',
            field=models.ManyToManyField(through='chamecoapi.PessoasAutorizadas', to='chamecoapi.usuarios'),
        ),
        migrations.CreateModel(
            name='UsuariosResponsaveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('superusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_responsaveis', to='chamecoapi.usuarios')),
            ],
            options={
                'verbose_name': 'Usuario Responsável',
                'verbose_name_plural': 'Usuarios Responsaveis',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Emprestimos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_emprestimo', models.DateTimeField(auto_now_add=True)),
                ('horario_devolucao', models.DateTimeField(null=True)),
                ('chave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos_de_chaves', to='chamecoapi.chaves')),
                ('usuario_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='emprestimos_solicitados', to='chamecoapi.usuarios')),
                ('usuario_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='emprestimos_responsaveis', to='chamecoapi.usuariosresponsaveis')),
            ],
            options={
                'verbose_name': 'Emprestimo',
                'verbose_name_plural': 'Emprestimos',
                'ordering': ['-id'],
            },
        ),
    ]
