# Generated by Django 5.1 on 2024-08-29 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blocos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Bloco',
                'verbose_name_plural': 'Blocos',
            },
        ),
        migrations.CreateModel(
            name='Chaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponivel', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Chave',
                'verbose_name_plural': 'Chaves',
            },
        ),
        migrations.CreateModel(
            name='PessoasAutorizadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamecoapi.chaves')),
            ],
        ),
        migrations.CreateModel(
            name='Salas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='chamecoapi.blocos')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
            },
        ),
        migrations.AddField(
            model_name='chaves',
            name='sala',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chave', to='chamecoapi.salas'),
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cortex', models.IntegerField()),
                ('id_setor', models.IntegerField()),
                ('id_tipo', models.IntegerField()),
                ('chaves_autorizadas', models.ManyToManyField(through='chamecoapi.PessoasAutorizadas', to='chamecoapi.chaves')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.AddField(
            model_name='pessoasautorizadas',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamecoapi.usuarios'),
        ),
        migrations.CreateModel(
            name='Emprestimos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_emprestimo', models.DateTimeField(auto_now_add=True)),
                ('horario_devolucao', models.DateTimeField(null=True)),
                ('chave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos_de_chaves', to='chamecoapi.chaves')),
                ('usuario_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos_responsaveis', to='chamecoapi.usuarios')),
                ('usuario_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos_solicitados', to='chamecoapi.usuarios')),
            ],
            options={
                'verbose_name': 'Emprestimo',
                'verbose_name_plural': 'Emprestimos',
            },
        ),
        migrations.AddField(
            model_name='chaves',
            name='usuarios_autorizados',
            field=models.ManyToManyField(through='chamecoapi.PessoasAutorizadas', to='chamecoapi.usuarios'),
        ),
    ]
