# Generated by Django 5.1 on 2024-09-03 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamecoapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='id_setor',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='id_tipo',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='setor',
            field=models.CharField(default='teste1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='tipo',
            field=models.CharField(default='teste1'),
            preserve_default=False,
        ),
    ]
