# Generated by Django 5.1 on 2025-04-06 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chamecoapi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chaves",
            name="sala",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chaves",
                to="chamecoapi.salas",
            ),
        ),
    ]
