# Generated by Django 5.1 on 2024-09-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamecoapi', '0002_remove_usuarios_id_setor_remove_usuarios_id_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='nome',
            field=models.CharField(default='teste'),
            preserve_default=False,
        ),
    ]
