# Generated by Django 5.1 on 2025-05-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamecoapi', '0002_alter_chaves_sala'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaves',
            name='descricao',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='emprestimos',
            name='observacao',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
