# Generated by Django 5.1 on 2025-08-07 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chamecoapi", "0003_chaves_descricao_emprestimos_observacao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuarios",
            name="autorizado_emprestimo",
        ),
    ]
