# Generated by Django 5.1 on 2025-09-13 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chamecoapi", "0004_remove_usuarios_autorizado_emprestimo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chaves",
            name="usuarios_autorizados",
        ),
        migrations.RemoveField(
            model_name="pessoasautorizadas",
            name="chave",
        ),
        migrations.RemoveField(
            model_name="usuarios",
            name="chaves_autorizadas",
        ),
        migrations.AddField(
            model_name="pessoasautorizadas",
            name="sala",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="chamecoapi.salas",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="salas",
            name="usuarios_autorizados",
            field=models.ManyToManyField(
                through="chamecoapi.PessoasAutorizadas", to="chamecoapi.usuarios"
            ),
        ),
        migrations.AddField(
            model_name="usuarios",
            name="salas_autorizadas",
            field=models.ManyToManyField(
                through="chamecoapi.PessoasAutorizadas", to="chamecoapi.salas"
            ),
        ),
    ]
