# Generated by Django 5.1 on 2024-11-01 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamecoapi', '0004_alter_usuarios_id_cortex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chaves',
            name='usuarios_autorizados',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='chaves_autorizadas',
        ),
        migrations.AlterModelOptions(
            name='blocos',
            options={'ordering': ['nome'], 'verbose_name': 'Bloco', 'verbose_name_plural': 'Blocos'},
        ),
        migrations.AlterModelOptions(
            name='chaves',
            options={'ordering': ['id'], 'verbose_name': 'Chave', 'verbose_name_plural': 'Chaves'},
        ),
        migrations.AlterModelOptions(
            name='emprestimos',
            options={'ordering': ['-id'], 'verbose_name': 'Emprestimo', 'verbose_name_plural': 'Emprestimos'},
        ),
        migrations.AlterModelOptions(
            name='salas',
            options={'ordering': ['nome'], 'verbose_name': 'Sala', 'verbose_name_plural': 'Salas'},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'ordering': ['id'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.CreateModel(
            name='UsuariosResponsaveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('superusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_responsaveis', to='chamecoapi.usuarios')),
            ],
        ),
        migrations.AlterField(
            model_name='emprestimos',
            name='usuario_responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='emprestimos_responsaveis', to='chamecoapi.usuariosresponsaveis'),
        ),
        migrations.DeleteModel(
            name='PessoasAutorizadas',
        ),
    ]
