# Generated by Django 5.1 on 2024-11-06 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamecoapi', '0005_remove_chaves_usuarios_autorizados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='autorizado_emprestimo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emprestimos',
            name='usuario_solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='emprestimos_solicitados', to='chamecoapi.usuarios'),
        ),
    ]
