# Generated by Django 5.1 on 2026-04-21 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamecoapi', '0005_remove_chaves_usuarios_autorizados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimos',
            name='usuario_responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emprestimos_responsaveis', to='chamecoapi.usuariosresponsaveis'),
        ),
        migrations.AlterField(
            model_name='emprestimos',
            name='usuario_solicitante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emprestimos_solicitados', to='chamecoapi.usuarios'),
        ),
    ]
