# Generated by Django 5.1 on 2026-05-28 18:37

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension

class Migration(migrations.Migration):

    dependencies = [
        ('chamecoapi', '0006_alter_emprestimos_usuario_responsavel_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            """CREATE EXTENSION IF NOT EXISTS unaccent;
            """
        ),
    ]
