# Generated by Django 5.1 on 2024-11-09 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamecoapi', '0006_usuarios_autorizado_emprestimo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuariosresponsaveis',
            options={'ordering': ['nome'], 'verbose_name': 'Usuario Responsável', 'verbose_name_plural': 'Usuarios Responsaveis'},
        ),
        migrations.CreateModel(
            name='PessoasAutorizadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamecoapi.chaves')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamecoapi.usuarios')),
            ],
        ),
        migrations.AddField(
            model_name='chaves',
            name='usuarios_autorizados',
            field=models.ManyToManyField(through='chamecoapi.PessoasAutorizadas', to='chamecoapi.usuarios'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='chaves_autorizadas',
            field=models.ManyToManyField(through='chamecoapi.PessoasAutorizadas', to='chamecoapi.chaves'),
        ),
    ]
