# Generated by Django 5.1 on 2024-11-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamecoapi', '0007_alter_usuariosresponsaveis_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaves',
            name='principal',
            field=models.BooleanField(default=False),
        ),
    ]
