# Generated by Django 5.1 on 2024-12-03 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamecoapi', '0009_tokens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokens',
            name='id_cortex',
        ),
        migrations.AddField(
            model_name='tokens',
            name='valor',
            field=models.CharField(default='1'),
            preserve_default=False,
        ),
    ]
