tipos_usa_sistema_livremente = [
    "admin",
    "ti",
    "motorista",
    "professor",
    "diretor.geral",
    "diretor.ensino",
    "coordenador",
    "tec.administrativo",
    "serv.terceirizado",
    "engenheiro",
    "enfermeiro",
    "medico",
    "psicologo",
    "nutricionista",
    "odontologo",
    "pedagogo",
    "vigilante",
]


setores_usa_sistema_livremente = [
    "direcao geral",
    "direcao de ensino",
    "direcao de administracao e planejamento",
    "coordenacao informatica",
    "coordenacao tec informatica",
    "coordenacao eletromecanica",
    "coordenacao tec eletromecanica",
    "coordenacao edificacoes",
    "coordenacao tec edificacoes",
    "coordenacao meio ambiente",
    "coordenacao tec meio ambiente",
    "coordenacao tads",
    "coordenacao biologia",
    "coordenacao matematica",
    "coordenacao profmat",
    "coordenacao de compras e licitacao",
    "coordenacao de controle academico",
    "coordenacao de disciplina",
    "coordenacao de ed. fisica",
    "coordenacao de extensao",
    "coordenacao de multimidia",
    "coordenacao de patrimônio e almoxarifado",
    "coordenacao de pesquisa e inovacao",
    "ti",
    "biblioteca",
    "casa da leitura",
    "departamento contabilidade",
    "departamento apoio ao ensino",
    "departamento logistica, manutencao e compras",
    "enfermagem",
    "engenharia",
    "nutricao",
    "psicologia",
    "saude",
    "servico social",
    "medico",
    "odontologico",
    "pedagogico",
    "refeitorio",
    "guarita",
    "area externa",
    "prof ens bas tec tecnologico-substituto",
    "assistente em administracao",
    "assistente de aluno",
    "tec de tecnologia da informacao",
    "professor ens basico tecn tecnologico",
    "engenheiro",
    "bibliotecario-documentalista",
    "vigilante",
    "tecnico em audiovisual",
    "contador",
    "auxiliar de biblioteca",
    "aux em administracao",
    "administrador",
    "enfermeiro",
    "tecnico em eletrotecnica",
    "tecnico de laboratorio",
    "psicologo",
    "tecnico em arquivo",
    "assistente social",
    "tecnico em assuntos educacionais",
    "odontologo",
    "secretario executivo",
    "pedagogo",
    "assistente de laboratorio",
    "medico",
    "nutricionista",
    "tecnico em enfermagem",
    "tecnico em secretariado",
    "analista de tec da informacao",
    "limpeza",
    "aux. cozinha",
]

tipos_admin = ["admin", "ti"]

setores_admin = ["ti"]
